import "./globals.css";
import "@repo/ui/styles.css";
import type { Metadata } from "next";
import { Titillium_Web } from "next/font/google";
import clsx from "clsx";
import { NavBar } from "./components";
import { auth } from "@/lib/auth";
import LogoutButton from "./components/logout-button";
import NavLink from "./components/nav-link";
import LogoLink from "./components/logo-link";

const fontFamily = Titillium_Web({
  subsets: ["latin"],
  weight: ["200", "300", "400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): Promise<JSX.Element> {
  const session = await auth();
  return (
    <html lang="en">
      <body className={clsx([fontFamily.className])}>
        {session ? (
          <NavBar />
        ) : (
          <div className="flex w-full items-end justify-between px-8 py-4 ">
            <LogoLink />
            <NavLink href="/login">Login</NavLink>
          </div>
        )}
        {children}
      </body>
    </html>
  );
}
