import "./globals.css";
import "@repo/ui/styles.css";
import type { Metadata } from "next";
import { Titillium_Web } from "next/font/google";
import clsx from "clsx";

const fontFamily = Titillium_Web({
  subsets: ["latin"],
  weight: ["200", "300", "400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): Promise<JSX.Element> {
  return (
    <html lang="en">
      <body className={clsx([fontFamily.className])}>{children}</body>
    </html>
  );
}
